project:
  type: website

website:
  title: "irumae"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ki5n2/irumae

format:
  html:
    embed-resources: true
    self-contained-math: true
    theme: cosmo
    css: styles.css
